server {
  listen 80;
  server_name ethanpewebsite.duckdns.org;

  if ($host = ethanpewebsite.duckdns.org) {
    return 301 https://$host$request_uri;
  }
}

server {
  listen 443 ssl;
  server_name ethanpewebsite.duckdns.org;

  location / {
    proxy_pass http://myportfolio:5000/;
  }

  limit_req_zone $binary_remote_addr zone=mylimit:10m rate=1r/m;
  location /timeline/ {
    limit_req zone=mylimit burst=20;
    proxy_pass http://myportfolio:5000/timeline/;
  }

  # Load the certificate files
  ssl_certificate /etc/letsencrypt/live/ethanpewebsite.duckdns.org/fullchain.pem;
  ssl_certificate_key /etc/letsencrypt/live/ethanpewebsite.duckdns.org/privkey.pem;
  ssl_trusted_certificate /etc/letsencrypt/live/ethanpewebsite.duckdns.org/chain.pem;
}